FROM ubuntu:22.04
MAINTAINER Manjunath
RUN apt-get update && apt-get install wget -y
RUN apt-get install openjdk-11-jdk -y
RUN mkdir tomcat
WORKDIR tomcat
RUN wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.96/bin/apache-tomcat-9.0.96.tar.gz
RUN tar -xvf apache-tomcat-9.0.96.tar.gz
COPY Amazon.war  /tomcat/apache-tomcat-9.0.93/webapps/
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "/tomcat/apache-tomcat-9.0.96/bin/catalina.sh run"]

